/* v35 adventure-depth pass: dungeon maps/compasses, treasure chests, minibosses, side quests, heart pieces */
ITEM_REWARD_LABEL.sageCharm='Sage Charm';
ITEM_REWARD_LABEL.hunterRing='Hunter Ring';
ITEM_REWARD_LABEL.villageSatchel='Village Satchel';
NPC_TEXT.npcElder=['Elder Rowan: Eight Ember Shards open the Ember Citadel. The old dungeons hide more than shards.','Elder Rowan: Four shards prove a traveler is ready for the Sage Charm.'];
NPC_TEXT.npcScout=['Trail Scout: The wilds keep returning. Defeat different threats across Emberwood and report back.','Trail Scout: A seasoned hunter learns the rhythm of every creature.'];
NPC_TEXT.npcChild=['Village Child: I collect bright meadow cuttings. Twenty patches should be enough for something useful!','Village Child: Some treasure chests are far from roads. Clear the danger before opening them.'];
const V35_DUNGEONS=[];
function addV35Dungeon(id,name,theme,keys,coords,boss){const d={id,name,theme,keys,coords,boss};V35_DUNGEONS.push(d);return d}
addV35Dungeon('gate','Ancient Gate','ruin',['gate0','gate1','gate2','gate3','gate4'],[[1,3],[1,2],[2,2],[2,3],[3,3]],'gate4');
addV35Dungeon('tide','Sunken Archive','tide',['tide0','tide1','tide2','tide3','tide4','tide5'],[[1,4],[1,3],[2,3],[2,2],[1,2],[1,1]],'tide5');
for(const def of DUNGEON_DEFS){const keys=Array.from({length:12},(_,i)=>def.p+i),coords=keys.map(k=>DUNGEON_COORDS[k]);addV35Dungeon(def.p,def.name,def.theme,keys,coords,def.p+'11')}
addV35Dungeon('citadel','Ember Citadel','citadel',Array.from({length:8},(_,i)=>'citadel'+i),citCoords,'citadel7');
const V35_DUNGEON_BY_ROOM={};for(const d of V35_DUNGEONS)for(const k of d.keys)V35_DUNGEON_BY_ROOM[k]=d;
function dungeonToken(kind,d){return `${kind}:${typeof d==='string'?d:d.id}`}
function hasDungeonMap(d){return G?.taken?.has(dungeonToken('dmap',d))}
function hasDungeonCompass(d){return G?.taken?.has(dungeonToken('dcompass',d))}
function markDungeonVisited(){if(insideKey&&V35_DUNGEON_BY_ROOM[insideKey])G.taken.add('visited:'+insideKey)}
const _v35EnterInterior=enterInterior;enterInterior=function(key){_v35EnterInterior(key);markDungeonVisited();saveGame()};
const _v35DungeonTransition=dungeonTransition;dungeonTransition=function(dx,dy){_v35DungeonTransition(dx,dy);markDungeonVisited();saveGame()};
const V35_MINIBOSSES={stoneSentinel:{name:'STONE SENTINEL',hp:10,theme:'ruin'},tideGuardian:{name:'TIDE GUARDIAN',hp:11,theme:'tide'},briarGolem:{name:'BRIAR GOLEM',hp:10,theme:'verdant'},prismKnight:{name:'PRISM KNIGHT',hp:11,theme:'crystal'},tempestDjinn:{name:'TEMPEST DJINN',hp:11,theme:'storm'},magmaBeast:{name:'MAGMA BEAST',hp:12,theme:'cinder'},duskStalker:{name:'DUSK STALKER',hp:11,theme:'moon'},crownWarden:{name:'CROWN WARDEN',hp:13,theme:'citadel'}};
const V35_MINI_ROOMS={gate2:'stoneSentinel',tide3:'tideGuardian',verdant6:'briarGolem',crystal6:'prismKnight',storm6:'tempestDjinn',cinder6:'magmaBeast',moon6:'duskStalker',citadel5:'crownWarden'};for(const [k,t] of Object.entries(V35_MINI_ROOMS))if(INTERIORS[k])INTERIORS[k].enemies=[t];
const _v35EnemyFactory=enemy;enemy=function(type,index,seed=0,worldId=null){const e=_v35EnemyFactory(type,index,seed,worldId),m=V35_MINIBOSSES[type];if(m){e.hp=e.maxHp=m.hp;e.bossTimer=42+(index%3)*7}return e};
const V35_CHESTS={};
function chestPos(room,seed=0){const f=ROOM_FEATURES[room]||{pillars:[],spikes:[],pots:[]},hit=(a,tx,ty)=>Array.isArray(a)&&a.some(p=>Array.isArray(p)&&p[0]===tx&&p[1]===ty),blocked=(tx,ty)=>hit(f.pillars,tx,ty)||hit(f.spikes,tx,ty)||hit(f.pots,tx,ty);const spots=[[8,8],[6,7],[10,7],[8,10],[5,9],[11,9],[8,6]];for(let n=0;n<spots.length;n++){const p=spots[(seed+n)%spots.length];if(!blocked(...p))return p}return[8,8]}
function addDungeonChest(room,kind,dungeon,seed=0){if(!room)return;const [x0,y0]=chestPos(room,seed);(V35_CHESTS[room]??=[]).push({scope:'dungeon',room,x:x0,y:y0,kind,dungeon:dungeon.id,token:`chest:${room}:${kind}`})}
for(let di=0;di<V35_DUNGEONS.length;di++){const d=V35_DUNGEONS[di],mapRoom=d.keys[1]||d.keys[0],compRoom=d.keys[Math.max(1,Math.min(d.keys.length-2,4))],supplyRoom=d.keys[d.keys.length>=10?7:d.keys.length>=8?3:2];addDungeonChest(mapRoom,'map',d,di);addDungeonChest(compRoom,'compass',d,di+2);if(supplyRoom!==mapRoom&&supplyRoom!==compRoom)addDungeonChest(supplyRoom,'supply',d,di+4)}
const V35_WORLD_CHEST_SCREENS=[2,19,30,39,60,71,89,95];
function pickWorldChest(i,n){const spots=[[5,7],[10,8],[4,10],[12,6],[6,4],[11,10],[3,7]];for(let q=0;q<spots.length;q++){const p=spots[(n+q)%spots.length];if(!WORLD[i].objects.some(o=>o.x===p[0]&&o.y===p[1]))return p}return[8,7]}
const V35_WORLD_CHESTS={};V35_WORLD_CHEST_SCREENS.forEach((i,n)=>{const p=pickWorldChest(i,n);V35_WORLD_CHESTS[i]={scope:'world',screen:i,x:p[0],y:p[1],kind:'heartPiece',token:`worldchest:${i}`}});
function currentChests(){if(insideKey)return V35_CHESTS[insideKey]||[];const c=V35_WORLD_CHESTS[id];return c?[c]:[]}
function chestOpened(c){return G.taken.has(c.token)}
function chestReady(c){return state().enemies.every(e=>e.hp<=0)}
function nearChest(){let best=null,dist=999;for(const c of currentChests()){const d=Math.hypot((x+8)-(c.x*T+8),(y+8)-(c.y*T+8));if(d<dist){best=c;dist=d}}return dist<27?best:null}
function giveChestReward(c){G.taken.add(c.token);sfx('secret');buzz([15,20,30]);effects.push({kind:'spark',x:c.x*T+8,y:c.y*T+7,t:0});if(c.kind==='map'){G.taken.add(dungeonToken('dmap',c.dungeon));say(`${V35_DUNGEONS.find(d=>d.id===c.dungeon)?.name||'Dungeon'} Map acquired!`,150)}else if(c.kind==='compass'){G.taken.add(dungeonToken('dcompass',c.dungeon));say('Compass acquired — boss and unopened treasure are marked.',160)}else if(c.kind==='supply'){const d=V35_DUNGEONS.find(d=>d.id===c.dungeon),n=V35_DUNGEONS.indexOf(d)%3;if(n===0){G.rupees=Math.min(999,G.rupees+40);say('Treasure chest: 40 rupees!')}else if(n===1){G.bombs=Math.min(G.maxBombs,G.bombs+5);say('Treasure chest: 5 bombs!')}else{G.magic=Math.min(G.maxMagic,G.magic+18);say('Treasure chest: magic restored!')}}else if(c.kind==='heartPiece'){const token=`heartPiece:${c.screen}`;G.taken.add(token);const count=[...G.taken].filter(t=>t.startsWith('heartPiece:')).length;if(count%4===0){G.maxHp=Math.min(14,G.maxHp+1);G.hp=G.maxHp;say('Four Heart Fragments joined — maximum health increased!',180)}else say(`Heart Fragment ${count%4}/4`,120)}saveGame()}
function interactChest(){const c=nearChest();if(!c)return false;if(chestOpened(c)){say('The chest is empty.',50);return true}if(!chestReady(c)){say('A strange seal remains while enemies are near.',75);return true}giveChestReward(c);return true}
const _v35SolidPixel=solidPixel;solidPixel=function(px,py){const tx=Math.floor(px/T),ty=Math.floor(py/T);for(const c of currentChests())if(!chestOpened(c)&&c.x===tx&&c.y===ty)return true;return _v35SolidPixel(px,py)};
function huntCount(){return [...G.taken].filter(t=>t.startsWith('hunt:')).length}
function grassCount(){return [...G.taken].filter(t=>t.startsWith('grass:')).length}
function heartPieceCount(){return [...G.taken].filter(t=>t.startsWith('heartPiece:')).length}
const _v35DropEnemy=dropEnemy;dropEnemy=function(e){if(!insideKey)G.taken.add(`hunt:${id}:${e.id}`);_v35DropEnemy(e)};
const _v35DamageEnemy=damageEnemy;damageEnemy=function(e,amount=1,ang=face){if(G?.items?.has('hunterRing')&&attack>0&&amount===1)amount=2;_v35DamageEnemy(e,amount,ang)};
function questNpc(o){if(o.type==='npcElder'){if(!G.taken.has('elderBlessing')){G.taken.add('elderBlessing');G.hp=G.maxHp;sfx('secret');say('Elder Rowan blesses your journey. Your strength is restored.',150);saveGame();return true}if(!G.taken.has('quest:elder')){if(G.shards<4){say(`Elder Rowan: Bring proof of four Ember Shards. You have ${G.shards}/4.`,145);return true}G.taken.add('quest:elder');G.items.add('sageCharm');G.maxMagic=Math.min(72,G.maxMagic+8);G.magic=G.maxMagic;sfx('secret');say('Elder Rowan grants the Sage Charm — maximum magic increased!',185);saveGame();return true}say('Elder Rowan: Eight shards open the Citadel. Trust the dungeon maps and your compass.',155);return true}if(o.type==='npcScout'){const n=huntCount();if(!G.taken.has('quest:scout')){if(n<15){say(`Trail Scout: Bounty progress ${n}/15 unique overworld threats.`,135);return true}G.taken.add('quest:scout');G.items.add('hunterRing');sfx('secret');say('Trail Scout awards the Hunter Ring — sword strikes hit harder!',175);saveGame();return true}say('Trail Scout: Keep the roads safe. Hidden chests appear quiet after a field is cleared.',150);return true}if(o.type==='npcChild'){const n=grassCount();if(!G.taken.has('quest:child')){if(n<20){say(`Village Child: Meadow cutting progress ${n}/20.`,120);return true}G.taken.add('quest:child');G.items.add('villageSatchel');G.maxBombs=Math.min(20,G.maxBombs+4);G.bombs=G.maxBombs;sfx('secret');say('Village Child gives you a reinforced satchel — bomb capacity increased!',180);saveGame();return true}say('Village Child: There are eight hidden Heart Fragments across Emberwood!',145);return true}return false}
const _v35TryTalk=tryTalkNpc;tryTalkNpc=function(){if(interactChest())return true;const o=nearbyNpc();if(o&&questNpc(o))return true;return _v35TryTalk()};
const _v35Update=update;update=function(){_v35Update();if(G&&insideKey&&V35_DUNGEON_BY_ROOM[insideKey])G.taken.add('visited:'+insideKey)};
const _v35Objective=objective;objective=function(){if(G.final)return _v35Objective();const q=(G.taken.has('quest:elder')?1:0)+(G.taken.has('quest:scout')?1:0)+(G.taken.has('quest:child')?1:0);return `${_v35Objective()} · Village quests ${q}/3 · Heart Fragments ${heartPieceCount()%4}/4`};