const C=document.querySelector('#game'),ctx=C.getContext('2d'),NAME=document.querySelector('#name'),STATS=document.querySelector('#stats'),HELP=document.querySelector('#help');ctx.imageSmoothingEnabled=false;
const KEYS=new Set(),T=16,WW=10,WH=10,DBG=true,SAVE_KEY='emberwood_save';
let audioCtx=null;function initAudio(){try{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}catch(e){}}function tone(f,d=.07,type='square',v=.025,when=0){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+when;o.type=type;o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+d)}function sfx(n){initAudio();if(n==='sword'){tone(620,.045,'square',.018);tone(410,.045,'square',.014,.035)}else if(n==='pickup'){tone(660,.055,'square',.02);tone(990,.075,'square',.018,.05)}else if(n==='hit'){tone(120,.05,'square',.02);tone(85,.06,'square',.015,.035)}else if(n==='shield'){tone(1100,.035,'square',.015);tone(1500,.05,'square',.012,.03)}else if(n==='bomb'){tone(75,.16,'sawtooth',.04);tone(48,.22,'square',.025,.025)}else if(n==='secret'){tone(440,.07,'square',.018);tone(660,.07,'square',.018,.07);tone(880,.1,'square',.018,.14)}else if(n==='place'){tone(180,.04,'square',.015)}else if(n==='door'){tone(280,.06,'square',.018);tone(350,.08,'square',.018,.06)}}function buzz(p=18){try{navigator.vibrate&&navigator.vibrate(p)}catch(e){}}
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;const on=e=>{e.preventDefault();initAudio();KEYS.add(k);b.classList.add('held')},off=e=>{e.preventDefault();KEYS.delete(k);b.classList.remove('held')};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off)});
addEventListener('keydown',e=>{initAudio();KEYS.add(e.code);if(e.code==='KeyM')toggleMap();if(e.code==='KeyQ')cycleItem()});addEventListener('keyup',e=>KEYS.delete(e.code));
const stick=document.querySelector('#stick'),knob=document.querySelector('#knob');let joyX=0,joyY=0,pointer=null;let gpX=0,gpY=0,gpA=false,gpB=false,gpMapLatch=false,gpItemLatch=false;
function stickMove(e){const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,R=r.width*.34;let x=e.clientX-cx,y=e.clientY-cy,m=Math.hypot(x,y);if(m>R){x*=R/m;y*=R/m}joyX=x/R;joyY=y/R;knob.style.transform=`translate(${x}px,${y}px)`}
stick.addEventListener('pointerdown',e=>{e.preventDefault();pointer=e.pointerId;stick.setPointerCapture(pointer);stickMove(e)});stick.addEventListener('pointermove',e=>{if(e.pointerId===pointer)stickMove(e)});function releaseStick(e){if(e.pointerId!==pointer)return;pointer=null;joyX=joyY=0;knob.style.transform='translate(0,0)'}stick.addEventListener('pointerup',releaseStick);stick.addEventListener('pointercancel',releaseStick);
function readGamepad(){gpX=gpY=0;gpA=gpB=false;const pads=navigator.getGamepads?navigator.getGamepads():[],p=[...pads].find(Boolean);if(!p)return;const dead=.18,ax=p.axes?.[0]||0,ay=p.axes?.[1]||0;gpX=Math.abs(ax)>dead?ax:0;gpY=Math.abs(ay)>dead?ay:0;gpA=!!p.buttons?.[0]?.pressed;gpB=!!p.buttons?.[1]?.pressed;const mapPressed=!!(p.buttons?.[8]?.pressed||p.buttons?.[9]?.pressed);if(mapPressed&&!gpMapLatch)toggleMap();gpMapLatch=mapPressed;const itemPressed=!!p.buttons?.[2]?.pressed;if(itemPressed&&!gpItemLatch)cycleItem();gpItemLatch=itemPressed}

function rng(n){let x=(n+1)*0x6D2B79F5;x=Math.imul(x^(x>>>15),x|1);x^=x+Math.imul(x^(x>>>7),x|61);return((x^(x>>>14))>>>0)/4294967296}
function makeScreen(i){const X=i%WW,Y=(i/WW)|0;let bi='field';if(Y<=1)bi=X<3?'ridge':X>6?'ash':'highland';else if(X<=1)bi='marsh';else if(X>=8&&Y>=5)bi='ruin';else if(Y>=8)bi='shadow';else if(X>=6&&Y<=4)bi='forest';else if((X*3+Y*5)%11<2)bi='ridge';
 const nameSets={field:['Greenfield','Windgrass','Fern Hollow','Sunmeadow','Foxglade','Clover Reach'],ridge:['Stonecrest','High Ridge','Boulder Run','Graypass','Iron Hills'],marsh:['Lakeward','Reedwater','Misty Shore','Blue Marsh','Riverbend'],shadow:['Duskmere','Gravefen','Ash Hollow','Nightfield','Old Barrows'],ruin:['Broken Court','Amber Ruins','Lost Rampart','Old Keep','Shattered Way'],forest:['Pineveil','Mosswood','Cedar Reach','Deepgrove','Owlwood'],ash:['Cinder Plain','Charred Reach','Ember Scar','Blackglass'],highland:['Northwind','Sky Meadow','Cloudstep','Frostgrass']};
 const arr=nameSets[bi],name=arr[(X*7+Y*11)%arr.length];
 const spots=[[3,3],[12,3],[3,10],[12,10],[6,4],[10,9],[5,11],[11,6],[8,4],[7,10]];let objects=[];const pool=bi==='ridge'?['rock','rock','tree']:bi==='marsh'?['water','water','reed']:bi==='shadow'?['grave','rock','grave']:bi==='ruin'?['ruin','rock','ruin']:bi==='forest'?['tree','tree','rock']:bi==='ash'?['rock','ruin','rock']:['tree','tree','rock'];
 const count=2+Math.floor(rng(i*17)*4);for(let j=0;j<count;j++){const p=spots[Math.floor(rng(i*97+j*23)*spots.length)],type=pool[Math.floor(rng(i*31+j*13)*pool.length)];if(!objects.some(o=>o.x===p[0]&&o.y===p[1]))objects.push({x:p[0],y:p[1],type})}
 const enemyPools=[['walker','hopper','shrub'],['shrub','walker','walker'],['hopper','walker','hopper','shrub'],['walker','walker','shrub','hopper'],['shrub','hopper','walker']];const enemies=enemyPools[(X+Y*2)%enemyPools.length].slice();
 return{name:`${name} ${Y+1}-${X+1}`,bi,objects,enemies};}
const WORLD=Array.from({length:100},(_,i)=>makeScreen(i));
function setScreen(i,name,bi,objects,enemies){WORLD[i]={name,bi,objects:objects.map(o=>({x:o[0],y:o[1],type:o[2]})),enemies}}
setScreen(9,'Ember Shrine','ash',[[8,2,'finalGate'],[4,9,'ruin'],[11,9,'ruin']],['walker','hopper','walker']);
setScreen(22,'Wayfarer Crossroads','field',[[8,4,'shop'],[3,10,'tree'],[12,10,'tree']],['shrub','walker']);
setScreen(44,'Whisper Ridge','ridge',[[3,3,'rock'],[9,4,'tree'],[12,9,'rock']],['walker','hopper','walker']);
setScreen(45,'Pinewatch','forest',[[3,3,'tree'],[4,3,'tree'],[11,3,'tree'],[10,10,'rock']],['walker','shrub','hopper']);
setScreen(46,'Bluewater','marsh',[[4,5,'water'],[5,5,'water'],[10,8,'water'],[11,8,'water']],['shrub','walker','hopper']);
setScreen(54,'Ember Meadow','field',[[3,2,'tree'],[12,2,'tree'],[5,9,'rock']],['walker','walker','shrub','hopper']);
setScreen(55,'Old Stone Road','ridge',[[2,4,'rock'],[3,4,'rock'],[12,9,'rock'],[3,10,'bombWall']],['walker','hopper','walker','shrub']);
setScreen(56,'Amber Ruins','ruin',[[4,3,'ruin'],[11,3,'ruin'],[4,10,'ruin'],[11,10,'pushRock']],['walker','walker','hopper','shrub']);
setScreen(64,'South Grove','forest',[[3,3,'tree'],[12,3,'tree'],[3,10,'tree'],[12,10,'tree']],['shrub','walker','hopper']);
setScreen(65,'Grave Path','shadow',[[4,4,'grave'],[8,3,'grave'],[11,9,'grave']],['walker','walker','walker','shrub']);
setScreen(66,'Ancient Gate','ruin',[[4,4,'ruin'],[11,4,'ruin'],[8,2,'lockedGate']],['walker','hopper','shrub','walker']);
setScreen(12,'Whispering Bluff','ridge',[[8,10,'bombWall'],[3,4,'rock'],[12,4,'rock']],['walker','hopper','walker']);
setScreen(31,'Mossy Hollow','forest',[[8,10,'pushRock'],[3,3,'tree'],[12,3,'tree']],['shrub','walker','hopper']);
setScreen(73,'Cinder Hollow','ash',[[8,10,'bombWall'],[4,4,'rock'],[11,5,'ruin']],['walker','walker','hopper']);
setScreen(88,'Old Barrow Field','shadow',[[8,10,'pushRock'],[4,4,'grave'],[11,4,'grave']],['walker','shrub','walker']);
setScreen(40,'Reedwind Bank','marsh',[[8,10,'bombWall'],[4,5,'reed'],[11,5,'water']],['shrub','hopper','walker']);

const PORTALS={'55:3:10':{inside:'grotto',method:'bomb',entrance:'cave'},'56:11:10':{inside:'lower',method:'push',entrance:'stairs'},'66:8:2':{inside:'gate0',method:'key',entrance:'door'},'22:8:4':{inside:'shop',method:'open',entrance:'shop'},'9:8:2':{inside:'shrine',method:'shards',entrance:'door'},'12:8:10':{inside:'cache',method:'bomb',entrance:'cave'},'31:8:10':{inside:'heartCave',method:'push',entrance:'stairs'},'73:8:10':{inside:'bombVault',method:'bomb',entrance:'cave'},'88:8:10':{inside:'barrow',method:'push',entrance:'stairs'},'40:8:10':{inside:'windCave',method:'bomb',entrance:'cave'}};
const INTERIORS={grotto:{name:'Buried Grotto',enemies:['walker','walker','hopper'],reward:'shard',exit:'cave',returnId:55,returnX:48,returnY:176},lower:{name:'Lower Ruins',enemies:['walker','shrub','walker'],reward:'shard',exit:'stairs',returnId:56,returnX:176,returnY:192},gate0:{name:'Ancient Gate - Entry Hall',enemies:['walker','walker'],reward:null,exit:'door',returnId:66,returnX:128,returnY:64,dungeon:true},gate1:{name:'Ancient Gate - North Hall',enemies:['shrub','walker'],reward:null,dungeon:true},gate2:{name:'Ancient Gate - Broken Gallery',enemies:['hopper','hopper','walker'],reward:null,dungeon:true},gate3:{name:'Ancient Gate - Sentinel Walk',enemies:['walker','shrub','hopper','walker'],reward:null,dungeon:true},gate4:{name:'Ancient Gate - Relic Vault',enemies:['warden'],reward:'shard',dungeon:true},shop:{name:"Mira's Supply Cave",enemies:[],reward:null,exit:'cave',returnId:22,returnX:128,returnY:96,shop:true},shrine:{name:'Ember Shrine',enemies:['warden'],reward:'relic',exit:'door',returnId:9,returnX:128,returnY:64,final:true},cache:{name:'Whispering Cache',enemies:['walker','hopper'],reward:'rupees20',exit:'cave',returnId:12,returnX:128,returnY:176},heartCave:{name:'Mossheart Chamber',enemies:['shrub','walker','hopper'],reward:'heartContainer',exit:'stairs',returnId:31,returnX:128,returnY:176},bombVault:{name:'Cinder Powder Vault',enemies:['walker','walker','hopper'],reward:'bombBag',exit:'cave',returnId:73,returnX:128,returnY:176},barrow:{name:'Old Barrow Treasury',enemies:['walker','shrub','walker','hopper'],reward:'rupees50',exit:'stairs',returnId:88,returnX:128,returnY:176},windCave:{name:'Reedwind Hollow',enemies:['shrub','hopper','walker'],reward:'windDisc',exit:'cave',returnId:40,returnX:128,returnY:176}};
const LANDMARKS={9:'Shrine',12:'Cache',22:'Shop',31:'Heart',55:'Cave',56:'Stairs',65:'Key',66:'Gate',73:'Bomb Bag',88:'Barrow',40:'Wind Disc'};
const ROADS=new Map();function roadPair(a,b){const ax=a%10,ay=(a/10)|0,bx=b%10,by=(b/10)|0,dx=Math.sign(bx-ax),dy=Math.sign(by-ay);if(!ROADS.has(a))ROADS.set(a,[]);if(!ROADS.has(b))ROADS.set(b,[]);ROADS.get(a).push([dx,dy]);ROADS.get(b).push([-dx,-dy])}
[[54,44,34,24,23,22],[54,55,56,66],[66,56,46,36,26,16,6,7,8,9],[54,64,74,73],[54,64,74,84,85,86,87,88],[54,53,52,42,32,31],[54,53,52,51,50,40],[54,44,34,24,14,13,12]].forEach(route=>{for(let i=0;i<route.length-1;i++)roadPair(route[i],route[i+1])});
const DUNGEON_LINKS={gate0:{U:'gate1'},gate1:{D:'gate0',R:'gate2'},gate2:{L:'gate1',D:'gate3'},gate3:{U:'gate2',R:'gate4'},gate4:{L:'gate3'}};
function dungeonLink(dir){return insideKey&&DUNGEON_LINKS[insideKey]?.[dir]||null}
