/* v36 dungeon puzzle pass: item-driven boss-wing rites without changing existing maps */
const V36_PUZZLES={};
// Repair rare malformed trap entries generated by older signed hash shifts.
for(const f of Object.values(ROOM_FEATURES)){f.spikes=(f.spikes||[]).filter(Array.isArray);f.pillars=(f.pillars||[]).filter(Array.isArray);f.pots=(f.pots||[]).filter(Array.isArray)}
function safePuzzleSpots(room,count){const f=ROOM_FEATURES[room]||{},blocked=(p)=>[...(f.pillars||[]),...(f.spikes||[]),...(f.pots||[])].some(q=>Array.isArray(q)&&q[0]===p[0]&&q[1]===p[1]),spots=[[5,6],[10,6],[8,10],[5,10],[11,9],[8,5],[4,8],[12,8]],out=[];for(const p of spots)if(!blocked(p)&&out.length<count)out.push(p);return out}
function addPuzzle(room,target,theme,requirements){const spots=safePuzzleSpots(room,requirements.length);V36_PUZZLES[room]={room,target,theme,nodes:requirements.map((req,i)=>({x:spots[i]?.[0]??(5+i*3),y:spots[i]?.[1]??8,req}))}}
addPuzzle('gate3','gate4','ruin',['sword','sword','sword']);
addPuzzle('tide4','tide5','tide',['tide','tide','tide']);
addPuzzle('verdant9','verdant11','verdant',['arrow','arrow','arrow']);
addPuzzle('crystal9','crystal11','crystal',['bomb','bomb','bomb']);
addPuzzle('storm9','storm11','storm',['disc','disc','disc']);
addPuzzle('cinder9','cinder11','cinder',['fire','fire','fire']);
addPuzzle('moon9','moon11','moon',['moon','moon','moon']);
addPuzzle('citadel5','citadel7','citadel',['bomb','disc','arrow','fire']);
delete DUNGEON_TRIALS[lockToken('citadel6','citadel7')];
DUNGEON_TRIALS[lockToken('citadel5','citadel7')]=['citadel2','citadel3','citadel6'];
const V36_GATES={};for(const p of Object.values(V36_PUZZLES))V36_GATES[lockToken(p.room,p.target)]=p.room;
function puzzleNodeToken(room,i){return`puzzleNode:${room}:${i}`}
function puzzleSolvedToken(room){return`puzzleSolved:${room}`}
function puzzleCount(p){let n=0;for(let i=0;i<p.nodes.length;i++)if(G.taken.has(puzzleNodeToken(p.room,i)))n++;return n}
function puzzleSolved(room){return G.taken.has(puzzleSolvedToken(room))}
function activatePuzzleNode(p,i){const tok=puzzleNodeToken(p.room,i);if(G.taken.has(tok))return false;G.taken.add(tok);effects.push({kind:'spark',x:p.nodes[i].x*T+8,y:p.nodes[i].y*T+8,t:0});sfx('secret');const n=puzzleCount(p);if(n===p.nodes.length){G.taken.add(puzzleSolvedToken(p.room));G.magic=Math.min(G.maxMagic,G.magic+8);say('The dungeon rite is complete — the boss wing opens!',180);screenShake=Math.max(screenShake,6)}else say(`Rune awakened ${n}/${p.nodes.length}`,75);saveGame();return true}
function currentPuzzle(){return insideKey?V36_PUZZLES[insideKey]:null}
function reqReady(req){if(req==='sword')return true;if(req==='arrow')return G.items.has('sunBow');if(req==='fire')return G.items.has('emberRod');if(req==='disc')return G.items.has('disc');if(req==='tide')return G.items.has('tideTunic');if(req==='moon')return G.items.has('moonRing');if(req==='bomb')return true;return false}
function hitPuzzleAt(kind,px,py){const p=currentPuzzle();if(!p)return false;let hit=false;for(let i=0;i<p.nodes.length;i++){const n=p.nodes[i];if(n.req!==kind||G.taken.has(puzzleNodeToken(p.room,i))||!reqReady(n.req))continue;if(Math.hypot(n.x*T+8-px,n.y*T+8-py)<15){activatePuzzleNode(p,i);hit=true}}return hit}
const _v36DungeonLink=dungeonLink;
dungeonLink=function(dir){const to=DUNGEON_LINKS[insideKey]?.[dir];if(!to)return null;const room=V36_GATES[lockToken(insideKey,to)];if(room&&!puzzleSolved(room))return null;return _v36DungeonLink(dir)};
const _v36Explode=explode;
explode=function(b){_v36Explode(b);hitPuzzleAt('bomb',b.x,b.y)};
function updatePuzzleRoom(){const p=currentPuzzle();if(!p||puzzleSolved(p.room))return;const sw=swordLine();if(sw)for(let i=0;i<p.nodes.length;i++){const n=p.nodes[i];if(n.req==='sword'&&!G.taken.has(puzzleNodeToken(p.room,i))&&segmentDistance(n.x*T+8,n.y*T+8,...sw)<11)activatePuzzleNode(p,i)}for(const z of waves)if(z.life>0&&(z.kind==='arrow'||z.kind==='fire'))hitPuzzleAt(z.kind,z.x,z.y);for(const d of discs)hitPuzzleAt('disc',d.x,d.y);for(let i=0;i<p.nodes.length;i++){const n=p.nodes[i];if(G.taken.has(puzzleNodeToken(p.room,i)))continue;if((n.req==='tide'||n.req==='moon')&&reqReady(n.req)&&Math.hypot(x+8-(n.x*T+8),y+8-(n.y*T+8))<15)activatePuzzleNode(p,i)}}
const _v36Update=update;
update=function(){_v36Update();if(!titleOpen&&!mapOpen&&!inventoryOpen&&!slide)updatePuzzleRoom()};
const _v36Objective=objective;
objective=function(){const p=currentPuzzle();if(p&&!puzzleSolved(p.room)){const need=[...new Set(p.nodes.filter((n,i)=>!G.taken.has(puzzleNodeToken(p.room,i))).map(n=>n.req))].map(r=>({sword:'sword',arrow:'Sun Bow',fire:'Ember Rod',disc:'Wind Disc',tide:'Tide Tunic',moon:'Moon Ring',bomb:'bombs'}[r]||r)).join(' / ');return `Dungeon rite ${puzzleCount(p)}/${p.nodes.length} · use ${need}`}_v36Objective()};