/* v30 HD atlas: 48px source art rendered 1:1 onto 3x canvas */
const HD=new Image();HD.src='atlas.svg';
const HD_BIOME={field:0,forest:1,ridge:2,marsh:3,shadow:4,ruin:5,ash:6,highland:7};
function hdCell(c,r,x,y,w=16,h=16){if(!HD.complete||!HD.naturalWidth)return false;ctx.drawImage(HD,c*48,r*48,48,48,x,y,w,h);return true}
const _hdTile=tile;tile=function(x,y,b){if(!hdCell(HD_BIOME[b]??0,0,x,y))_hdTile(x,y,b)};
const _hdTree=tree;tree=function(x,y){if(!hdCell(0,1,x,y))_hdTree(x,y)};const _hdRock=rock;rock=function(x,y){if(!hdCell(1,1,x,y))_hdRock(x,y)};const _hdWater=water;water=function(x,y){if(!hdCell(2,1,x,y))_hdWater(x,y)};const _hdRuin=ruin;ruin=function(x,y){if(!hdCell(3,1,x,y))_hdRuin(x,y)};const _hdGrave=grave;grave=function(x,y){if(!hdCell(4,1,x,y))_hdGrave(x,y)};const _hdReed=reed;reed=function(x,y){if(!hdCell(5,1,x,y))_hdReed(x,y)};const _hdCave=cave;cave=function(x,y){if(!hdCell(6,1,x,y))_hdCave(x,y)};const _hdStairs=stairs;stairs=function(x,y){if(!hdCell(7,1,x,y))_hdStairs(x,y)};
const _hdHero=drawHero;drawHero=function(){if(!HD.complete||!HD.naturalWidth)return _hdHero();if(invuln&&((invuln/4)|0)%2)return;const oi={traveler:0,tideTunic:1,emberTunic:2,shadowCloak:3}[G.outfit]??0,dx=Math.abs(Math.cos(face))>Math.abs(Math.sin(face))?(Math.cos(face)<0?2:3):(Math.sin(face)<0?1:0),fr=((walk/5)|0)%2,c=dx*2+fr;shadowBlob(x+8,y+15,13,4,.20);hdCell(c,2+oi,x-1,y-2,18,18);if(chargeFrames>10&&!attack){const p=Math.min(1,chargeFrames/42);ctx.strokeStyle=`rgba(255,235,145,${.16+p*.45})`;ctx.lineWidth=1;ctx.beginPath();ctx.arc(x+8,y+8,12+p*5,-Math.PI/2,-Math.PI/2+Math.PI*2*p);ctx.stroke()}};
const HD_ENEMY={walker:0,knight:1,slime:2,bat:3,hopper:4,shrub:5,warden:6};const HD_BOSS={rootLord:0,crystalMaw:1,stormEye:2,forgeLord:3,moonKnight:4};const _hdEnemy=drawEnemy;drawEnemy=function(e){if(!HD.complete||!HD.naturalWidth)return _hdEnemy(e);if(e.flash&&((e.flash/2)|0)%2)return;if(e.maxHp){const c=HD_BOSS[e.type];if(c!=null){shadowBlob(e.x+7,e.y+15,15,4,.25);return hdCell(c,8,e.x-2,e.y-3,19,19)}}const c=HD_ENEMY[e.type];if(c==null)return _hdEnemy(e);const fr=((performance.now()/130)|0)%2;shadowBlob(e.x+7,e.y+15,13,4,.18);hdCell(c,6+fr,e.x-2,e.y-3,18,18)};
const _hdDrops=drawDrops;drawDrops=function(){_hdDrops();if(!HD.complete||!HD.naturalWidth)return;for(const d of state().drops){if(d.got)continue;const map={sunBow:2,emberRod:3,masterKey:4,mirrorShield:5,stormBoots:6};const c=map[d.type];if(c!=null)hdCell(c,9,d.x-8,d.y-8,16,16)}};
const _hdFrame=draw;draw=function(){_hdFrame();};