function neighbor(i,dx,dy){const X=i%WW,Y=(i/WW)|0,nx=X+dx,ny=Y+dy;return nx<0||ny<0||nx>=WW||ny>=WH?null:ny*WW+nx}
function objectAt(i,tx,ty){return WORLD[i].objects.find(o=>o.x===tx&&o.y===ty)}function worldKey(i,x,y){return`${i}:${x}:${y}`}
function enemySpot(worldId,index){const spots=[[4,4],[11,4],[4,9],[11,9],[8,6],[6,11],[10,11],[8,3],[5,6],[10,6]];if(worldId==null){const p=spots[index%spots.length];return{x:p[0]*T,y:p[1]*T}}for(let n=0;n<spots.length;n++){const p=spots[(index+n)%spots.length],blocked=WORLD[worldId].objects.some(o=>o.x===p[0]&&o.y===p[1]);if(!blocked)return{x:p[0]*T,y:p[1]*T}}return{x:128,y:112}}
function enemy(type,index,seed=0,worldId=null){const p=enemySpot(worldId,index);return{type,x:p.x,y:p.y,hp:type==='hopper'?3:type==='warden'?10:2,dir:index%4,timer:30+Math.floor(rng(index+seed)*80),flash:0,hit:false,id:`${seed}-${index}-${type}`}}
function roomState(types,seed,worldId=null){return{enemies:types.map((t,i)=>enemy(t,i,seed,worldId)),drops:[],cleared:false,rewarded:false,keySpawned:false}}
let G,id,insideKey,x,y,face,walk,attack,attackLatch,bombLatch,invuln,bombObjs,waves,effects,transitionCooldown,message,messageTimer,push,mapOpen,slide,shopCursor,screenShake,lastSave=0;
function baseGame(){return{hp:3,maxHp:3,bombs:0,maxBombs:8,keys:0,rupees:0,shards:0,open:[],moved:[],unlocked:[],positions:{},taken:[],visited:[54],final:false,worldStates:WORLD.map((s,i)=>roomState(s.enemies,i,i)),interiorStates:{}}}
function hydrateSets(){G.open=new Set(G.open||[]);G.moved=new Set(G.moved||[]);G.unlocked=new Set(G.unlocked||[]);G.taken=new Set(G.taken||[]);G.visited=new Set(G.visited||[])}
function newGame(clear=false){if(clear)localStorage.removeItem(SAVE_KEY);G=baseGame();hydrateSets();for(const k in INTERIORS)G.interiorStates[k]=roomState(INTERIORS[k].enemies,1000+Object.keys(INTERIORS).indexOf(k));G.worldStates[54].enemies[0].guaranteed='bomb3';id=54;insideKey='';x=120;y=160;face=-Math.PI/2;walk=attack=invuln=transitionCooldown=0;attackLatch=bombLatch=false;bombObjs=[];waves=[];effects=[];message='Explore Emberwood';messageTimer=120;push={key:'',frames:0};mapOpen=false;slide=null;shopCursor=0;screenShake=0;saveGame()}
function savePayload(){return{version:15,hp:G.hp,maxHp:G.maxHp,bombs:G.bombs,maxBombs:G.maxBombs,keys:G.keys,rupees:G.rupees,shards:G.shards,open:[...G.open],moved:[...G.moved],unlocked:[...G.unlocked],positions:G.positions,taken:[...G.taken],visited:[...G.visited],final:G.final,id,insideKey,x,y}}
function saveGame(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(savePayload()));lastSave=performance.now()}catch(e){}}
function loadGame(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return false;const s=JSON.parse(raw);if(s.version!==15)return false;G=baseGame();hydrateSets();for(const k in INTERIORS)G.interiorStates[k]=roomState(INTERIORS[k].enemies,1000+Object.keys(INTERIORS).indexOf(k));G.worldStates[54].enemies[0].guaranteed='bomb3';Object.assign(G,{hp:s.hp,maxHp:s.maxHp,bombs:s.bombs,maxBombs:s.maxBombs??8,keys:s.keys,rupees:s.rupees,shards:s.shards,positions:s.positions||{},final:!!s.final});G.open=new Set(s.open||[]);G.moved=new Set(s.moved||[]);G.unlocked=new Set(s.unlocked||[]);G.taken=new Set(s.taken||[]);G.visited=new Set(s.visited||[54]);id=s.id??54;insideKey=s.insideKey||'';x=s.x??120;y=s.y??160;face=-Math.PI/2;walk=attack=invuln=transitionCooldown=0;attackLatch=bombLatch=false;bombObjs=[];waves=[];effects=[];message='Progress restored';messageTimer=80;push={key:'',frames:0};mapOpen=false;slide=null;shopCursor=0;screenShake=0;lastSave=performance.now();return true}catch(e){return false}}
function say(text,time=110){message=text;messageTimer=time}function state(){return insideKey?G.interiorStates[insideKey]:G.worldStates[id]}
function movedRockAt(i,tx,ty){for(const o of WORLD[i].objects)if(o.type==='pushRock'){const k=worldKey(i,o.x,o.y),p=G.positions[k]||{x:o.x,y:o.y};if(p.x===tx&&p.y===ty)return{k,o,p}}}
function portalReady(k,p){return p.method==='open'||(p.method==='bomb'&&G.open.has(k))||(p.method==='push'&&G.moved.has(k))||(p.method==='key'&&G.unlocked.has(k))||(p.method==='shards'&&G.shards>=3)}
function baseSolid(i,tx,ty){if(tx<0||ty<0||tx>15||ty>14)return false;if(movedRockAt(i,tx,ty))return true;const o=objectAt(i,tx,ty);if(!o)return false;const k=worldKey(i,tx,ty);if(o.type==='bombWall')return !G.open.has(k);if(o.type==='pushRock')return !G.moved.has(k);if(o.type==='lockedGate')return !G.unlocked.has(k);if(o.type==='finalGate')return G.shards<3;return['tree','rock','water','ruin','grave','reed'].includes(o.type)}
function solidPixel(px,py){if(insideKey){const info=INTERIORS[insideKey];if(info?.dungeon){if(px<16)return !dungeonLink('L')||py<96||py>160;if(px>239)return !dungeonLink('R')||py<96||py>160;if(py<16)return !dungeonLink('U')||px<96||px>160;if(py>223)return !dungeonLink('D')||px<96||px>160;return false}return px<16||px>239||py<16||py>223}const tx=Math.floor(px/T),ty=Math.floor(py/T);if(px<0)return neighbor(id,-1,0)==null||py<96||py>160;if(px>255)return neighbor(id,1,0)==null||py<96||py>160;if(py<0)return neighbor(id,0,-1)==null||px<96||px>160;if(py>239)return neighbor(id,0,1)==null||px<96||px>160;return baseSolid(id,tx,ty)}
function canMove(nx,ny){return !solidPixel(nx+4,ny+4)&&!solidPixel(nx+12,ny+4)&&!solidPixel(nx+4,ny+12)&&!solidPixel(nx+12,ny+12)}
function enemyCanMove(nx,ny){return !solidPixel(nx+3,ny+3)&&!solidPixel(nx+11,ny+12)}
function safeFloor(ri,preferX=8,preferY=7){for(let r=0;r<7;r++)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){const tx=preferX+dx,ty=preferY+dy;if(tx>1&&tx<14&&ty>1&&ty<13&&!baseSolid(ri,tx,ty))return{x:tx*T,y:ty*T}}return{x:120,y:112}}
function startSlide(dx,dy){if(slide||insideKey)return;const to=neighbor(id,dx,dy);if(to==null)return;slide={from:id,to,dx,dy,frame:0,total:16};transitionCooldown=20}
function finishSlide(){const s=slide;id=s.to;G.visited.add(id);if(s.dx<0)x=232;if(s.dx>0)x=8;if(s.dy<0)y=216;if(s.dy>0)y=8;slide=null;say(WORLD[id].name,70);saveGame()}
function enterInterior(key){sfx(INTERIORS[key].exit==='stairs'?'secret':'door');insideKey=key;x=120;y=176;transitionCooldown=28;bombObjs=[];waves=[];effects=[];say(INTERIORS[key].name,90);saveGame()}
function leaveInterior(){const info=INTERIORS[insideKey];sfx(info.exit==='stairs'?'secret':'door');insideKey='';id=info.returnId;x=info.returnX;y=info.returnY;transitionCooldown=34;bombObjs=[];waves=[];effects=[];G.visited.add(id);say(WORLD[id].name,70);saveGame()}
function dungeonTransition(dx,dy){const dir=dx<0?'L':dx>0?'R':dy<0?'U':'D',to=dungeonLink(dir);if(!to)return;insideKey=to;if(dx<0)x=224;if(dx>0)x=16;if(dy<0)y=208;if(dy>0)y=16;transitionCooldown=20;bombObjs=[];waves=[];effects=[];say(INTERIORS[to].name,60);saveGame()}

function checkPortal(){if(insideKey||transitionCooldown||slide)return;const tx=Math.floor((x+8)/T),ty=Math.floor((y+8)/T),k=worldKey(id,tx,ty),p=PORTALS[k];if(p&&portalReady(k,p))enterInterior(p.inside)}
function unlockNearby(){if(insideKey||!G.keys)return;const tx=Math.floor((x+8)/T),ty=Math.floor((y+8)/T);for(const k in PORTALS){const p=PORTALS[k],[ri,px,py]=k.split(':').map(Number);if(ri===id&&p.method==='key'&&!G.unlocked.has(k)&&Math.abs(tx-px)+Math.abs(ty-py)<=1){G.keys--;G.unlocked.add(k);sfx('door');say('The ancient lock opens.');saveGame()}}}
function swordLine(){if(!attack)return null;const p=(14-attack)/14,reach=8+19*Math.sin(Math.PI*p),cx=x+8,cy=y+8;return[cx+Math.cos(face)*6,cy+Math.sin(face)*6,cx+Math.cos(face)*reach,cy+Math.sin(face)*reach]}
function segmentDistance(px,py,a,b,c,d){const vx=c-a,vy=d-b,t0=((px-a)*vx+(py-b)*vy)/(vx*vx+vy*vy||1),t=Math.max(0,Math.min(1,t0));return Math.hypot(px-(a+t*vx),py-(b+t*vy))}
function damageEnemy(e,amount=1,ang=face){if(e.hp<=0)return;e.hp-=amount;sfx('hit');e.flash=8;for(let i=0;i<5;i++){const nx=e.x+Math.cos(ang),ny=e.y+Math.sin(ang);if(!enemyCanMove(nx,ny))break;e.x=nx;e.y=ny}if(e.hp<=0)dropEnemy(e)}
function dropEnemy(e){const R=state();if(e.guaranteed==='bomb3'){R.drops.push({x:e.x+7,y:e.y+7,type:'bomb3'});return}const roll=Math.random();if(roll<.36)R.drops.push({x:e.x+7,y:e.y+7,type:'rupee',value:roll<.06?5:1});else if(roll<.52)R.drops.push({x:e.x+7,y:e.y+7,type:'heart'});else if(roll<.65)R.drops.push({x:e.x+7,y:e.y+7,type:'bomb'})}
function updateEnemies(){const R=state(),dirs=[[1,0],[0,1],[-1,0],[0,-1]];for(const e of R.enemies){if(e.hp<=0)continue;if(e.flash)e.flash--;if(e.type==='shrub'){e.timer--;if(e.timer<=0){e.timer=80+Math.random()*80;e.dir=(Math.random()*4)|0;if(Math.random()<.35){const d=dirs[e.dir];waves.push({x:e.x+7,y:e.y+7,vx:d[0]*1.15,vy:d[1]*1.15,life:90,enemy:true})}}continue}if(e.type==='hopper'){e.timer--;if(e.timer<=0){e.timer=45+Math.random()*55;e.dir=(Math.random()*4)|0}if(e.timer%28>12)continue}else{e.timer--;if(e.timer<=0){e.timer=35+Math.random()*100;e.dir=(Math.random()*4)|0}}const d=dirs[e.dir],speed=e.type==='warden'?.55:e.type==='hopper'?.7:.42,nx=e.x+d[0]*speed,ny=e.y+d[1]*speed;if(nx<20||ny<20||nx>222||ny>206||!enemyCanMove(nx,ny))e.dir=(e.dir+2)%4;else{e.x=nx;e.y=ny}if(!invuln&&Math.hypot(x+8-e.x-7,y+8-e.y-7)<12){G.hp--;invuln=65;sfx('hit');buzz(35);const a=Math.atan2(y-e.y,x-e.x);for(let j=0;j<8;j++){const nx=x+Math.cos(a),ny=y+Math.sin(a);if(!canMove(nx,ny))break;x=nx;y=ny}if(G.hp<=0){G.hp=G.maxHp;const pos=safeFloor(id);x=pos.x;y=pos.y;say('You awaken at the last trail.');saveGame()}}}
 if(!R.cleared&&R.enemies.every(e=>e.hp<=0)){R.cleared=true;if(!insideKey&&id===65&&!R.keySpawned){R.keySpawned=true;R.drops.push({x:128,y:112,type:'key'});say('A key appears!')}if(insideKey&&!R.rewarded){R.rewarded=true;const info=INTERIORS[insideKey];if(info.reward==='shard'&&!G.taken.has(`reward:${insideKey}`)){R.drops.push({x:128,y:104,type:'shard',key:`reward:${insideKey}`});say('An Ember Shard appears!')}else if(info.reward==='rupees20'&&!G.taken.has(`reward:${insideKey}`)){R.drops.push({x:128,y:104,type:'rupeeChest',value:20,key:`reward:${insideKey}`});say('A treasure cache appears!')}else if(info.reward==='rupees50'&&!G.taken.has(`reward:${insideKey}`)){R.drops.push({x:128,y:104,type:'rupeeChest',value:50,key:`reward:${insideKey}`});say('An ancient treasure appears!')}else if(info.reward==='heartContainer'&&!G.taken.has(`reward:${insideKey}`)){R.drops.push({x:128,y:104,type:'heartContainer',key:`reward:${insideKey}`});say('A Heart Vessel appears!')}else if(info.reward==='bombBag'&&!G.taken.has(`reward:${insideKey}`)){R.drops.push({x:128,y:104,type:'bombBag',key:`reward:${insideKey}`});say('An old powder satchel appears!')}if(info.reward==='relic'&&!G.final){R.drops.push({x:128,y:104,type:'relic',key:'finalRelic'});say('The Ember Relic is revealed!',160)}}}}
function updateDrops(){for(const d of state().drops){if(d.got)continue;if(Math.hypot(x+8-d.x,y+8-d.y)<13){d.got=true;sfx(d.type==='shard'||d.type==='relic'?'secret':'pickup');if(['shard','relic','heartContainer','bombBag'].includes(d.type))buzz([18,25,18]);if(d.type==='heart')G.hp=Math.min(G.maxHp,G.hp+1);else if(d.type==='bomb')G.bombs=Math.min(G.maxBombs,G.bombs+1);else if(d.type==='bomb3')G.bombs=Math.min(G.maxBombs,G.bombs+3);else if(d.type==='key')G.keys++;else if(d.type==='rupee')G.rupees=Math.min(999,G.rupees+(d.value||1));else if(d.type==='rupeeChest'){G.rupees=Math.min(999,G.rupees+(d.value||0));G.taken.add(d.key);say(`${d.value} rupees found!`)}else if(d.type==='heartContainer'){G.taken.add(d.key);G.maxHp=Math.min(8,G.maxHp+1);G.hp=G.maxHp;say('Maximum health increased!')}else if(d.type==='bombBag'){G.taken.add(d.key);G.maxBombs=Math.min(16,G.maxBombs+4);G.bombs=G.maxBombs;say('Bomb capacity increased!')}else if(d.type==='shard'){if(!G.taken.has(d.key)){G.taken.add(d.key);G.shards++;say(`Ember Shard ${G.shards}/3 acquired!`,130)}}else if(d.type==='relic'){G.final=true;G.taken.add(d.key);say('THE EMBER RELIC IS RESTORED!',240)}saveGame()}}}
function placeBomb(){if(!G.bombs)return say('No bombs');G.bombs--;sfx('place');bombObjs.push({x:x+8+Math.cos(face)*16,y:y+8+Math.sin(face)*16,fuse:70});saveGame()}
function explode(b){sfx('bomb');buzz([20,35,55]);screenShake=12;effects.push({x:b.x,y:b.y,t:0});for(const e of state().enemies)if(e.hp>0&&Math.hypot(e.x+7-b.x,e.y+7-b.y)<42)damageEnemy(e,2,Math.atan2(e.y+7-b.y,e.x+7-b.x));if(!insideKey)for(const k in PORTALS){const p=PORTALS[k],[ri,tx,ty]=k.split(':').map(Number);if(ri===id&&p.method==='bomb'&&!G.open.has(k)&&Math.hypot(tx*T+8-b.x,ty*T+8-b.y)<45){G.open.add(k);sfx('secret');say('A dark passage opens!');saveGame()}}}
function pushRock(dx,dy){if(insideKey)return;let X=0,Y=0;if(Math.abs(dx)>=Math.abs(dy))X=Math.sign(dx);else Y=Math.sign(dy);const tx=Math.floor((x+8+X*13)/T),ty=Math.floor((y+8+Y*13)/T),P=movedRockAt(id,tx,ty);if(!P){push={key:'',frames:0};return}const token=P.k+':'+X+':'+Y;if(push.key!==token)push={key:token,frames:1};else push.frames++;if(push.frames>95&&!baseSolid(id,tx+X,ty+Y)&&!movedRockAt(id,tx+X,ty+Y)){G.moved.add(P.k);G.positions[P.k]={x:tx+X,y:ty+Y};sfx('secret');say('The stone grinds aside.');push.frames=0;saveGame()}}
function updateWaves(){for(const z of waves){z.x+=z.vx;z.y+=z.vy;z.life--;if(solidPixel(z.x,z.y)){z.life=0;continue}if(z.enemy){if(Math.hypot(x+8-z.x,y+8-z.y)<9){const vx=z.x-(x+8),vy=z.y-(y+8),m=Math.hypot(vx,vy)||1,dot=Math.cos(face)*(vx/m)+Math.sin(face)*(vy/m);if(!attack&&dot>.25){z.life=0;effects.push({x:z.x,y:z.y,t:18,small:true});sfx('shield')}else if(!invuln){G.hp--;invuln=55;z.life=0;sfx('hit');buzz(30);if(G.hp<=0){G.hp=G.maxHp;const p=insideKey?{x:120,y:176}:safeFloor(id);x=p.x;y=p.y}}}}else for(const e of state().enemies)if(z.life>0&&e.hp>0&&Math.hypot(e.x+7-z.x,e.y+7-z.y)<10){damageEnemy(e);z.life=0}}waves=waves.filter(z=>z.life>0)}
function shopUpdate(){if(insideKey!=='shop')return;const A=KEYS.has('Space')||KEYS.has('Enter')||gpA;if(A&&!attackLatch){const choices=[{cost:5,text:'Heal',buy:()=>G.hp=G.maxHp},{cost:10,text:'3 Bombs',buy:()=>G.bombs=Math.min(G.maxBombs,G.bombs+3)},{cost:30,text:'Heart',key:'heartUpgrade',buy:()=>{G.maxHp=Math.min(8,G.maxHp+1);G.hp=G.maxHp}}],c=choices[shopCursor];if(c.key&&G.taken.has(c.key))say('Already purchased.');else if(G.rupees<c.cost)say('Not enough rupees.');else{G.rupees-=c.cost;c.buy();if(c.key)G.taken.add(c.key);say(`${c.text} purchased.`);saveGame()}}}
function objective(){if(G.final)return'Relic restored — explore freely';if(G.shards>=3)return'Follow the old roads northeast to the Ember Shrine';if(G.shards===2)return'One shard remains — the Ancient Gate lies southeast of the central road';if(G.shards===1)return'Two shards remain — roads lead toward ruins, caves, and old locks';return'Find 3 Ember Shards · old roads connect important landmarks'}
function update(){readGamepad();if(screenShake)screenShake--;if(mapOpen)return;if(slide){if(++slide.frame>=slide.total)finishSlide();return}if(transitionCooldown)transitionCooldown--;if(invuln)invuln--;if(messageTimer)messageTimer--;let dx=joyX+gpX,dy=joyY+gpY;if(KEYS.has('ArrowLeft')||KEYS.has('KeyA'))dx--;if(KEYS.has('ArrowRight')||KEYS.has('KeyD'))dx++;if(KEYS.has('ArrowUp')||KEYS.has('KeyW'))dy--;if(KEYS.has('ArrowDown')||KEYS.has('KeyS'))dy++;const m=Math.hypot(dx,dy);if(m>.08){dx/=Math.max(1,m);dy/=Math.max(1,m);face=Math.atan2(dy,dx);const speed=attack?.68:1.35,nx=x+dx*speed,ny=y+dy*speed;if(canMove(nx,y))x=nx;if(canMove(x,ny))y=ny;walk+=speed;pushRock(dx,dy)}else push={key:'',frames:0};
 if(!insideKey){if(x<-6)startSlide(-1,0);else if(x>246)startSlide(1,0);else if(y<-6)startSlide(0,-1);else if(y>230)startSlide(0,1)}else if(INTERIORS[insideKey]?.dungeon){if(!transitionCooldown){if(x<8&&dungeonLink('L'))dungeonTransition(-1,0);else if(x>232&&dungeonLink('R'))dungeonTransition(1,0);else if(y<8&&dungeonLink('U'))dungeonTransition(0,-1);else if(y>216&&dungeonLink('D'))dungeonTransition(0,1);else if(insideKey==='gate0'&&y>194&&x>104&&x<144)leaveInterior()}}else if(!transitionCooldown&&y>194&&x>104&&x<144)leaveInterior();checkPortal();unlockNearby();
 const A=KEYS.has('Space')||KEYS.has('Enter')||gpA;if(insideKey==='shop'){if(KEYS.has('ArrowLeft')||joyX<-.6)shopCursor=0;if(KEYS.has('ArrowUp')||joyY<-.6)shopCursor=1;if(KEYS.has('ArrowRight')||joyX>.6)shopCursor=2;shopUpdate()}else if(A&&!attackLatch&&!attack){sfx('sword');attack=14;for(const e of state().enemies)e.hit=false;if(G.hp===G.maxHp)waves.push({x:x+8+Math.cos(face)*18,y:y+8+Math.sin(face)*18,vx:Math.cos(face)*2.5,vy:Math.sin(face)*2.5,life:55,enemy:false})}attackLatch=A;if(attack)attack--;const B=KEYS.has('KeyB')||KEYS.has('ShiftLeft')||gpB;if(B&&!bombLatch&&insideKey!=='shop')placeBomb();bombLatch=B;
 const sw=swordLine();for(const e of state().enemies){if(!sw){e.hit=false;continue}if(e.hp>0&&!e.hit&&segmentDistance(e.x+7,e.y+7,...sw)<11){e.hit=true;damageEnemy(e)}}updateEnemies();updateDrops();for(const b of bombObjs)if(--b.fuse===0)explode(b);bombObjs=bombObjs.filter(b=>b.fuse>0);for(const f of effects)f.t++;effects=effects.filter(f=>f.t<32);updateWaves();if(performance.now()-lastSave>5000)saveGame()}
