/* v36 recovery: restore state behavior lost in mixed v35/v36 deployment */
enemy=function(type,index,seed=0,worldId=null){const p=enemySpot(worldId,index);return{type,x:p.x,y:p.y,hp:type==='warden'?10:type==='knight'?4:type==='slime'?3:type==='hopper'?3:2,dir:index%4,timer:30+Math.floor(rng(index+seed)*80),flash:0,stun:0,hit:false,id:`${seed}-${index}-${type}`}};
baseSolid=function(i,tx,ty){if(tx<0||ty<0||tx>15||ty>14)return false;if(movedRockAt(i,tx,ty))return true;const o=objectAt(i,tx,ty);if(!o)return false;const k=worldKey(i,tx,ty);if(o.type==='bombWall')return !G.open.has(k);if(o.type==='pushRock')return !G.moved.has(k);if(o.type==='lockedGate')return !G.unlocked.has(k);if(o.type==='finalGate')return G.shards<3;return['tree','rock','water','ruin','grave','reed','house','well','npcElder','npcScout','npcChild'].includes(o.type)};
swordLine=function(){if(!attack)return null;const p=(14-attack)/14,bonus=G?.taken?.has('reward:tide5')?6:0,reach=8+(19+bonus)*Math.sin(Math.PI*p),cx=x+8,cy=y+8;return[cx+Math.cos(face)*6,cy+Math.sin(face)*6,cx+Math.cos(face)*reach,cy+Math.sin(face)*reach]};
updateDrops=function(){for(const d of state().drops){if(d.got)continue;if(Math.hypot(x+8-d.x,y+8-d.y)<13){d.got=true;sfx(d.type==='shard'||d.type==='relic'?'secret':'pickup');if(['shard','relic','heartContainer','bombBag','windDisc','bladeCharm'].includes(d.type))buzz([18,25,18]);if(d.type==='heart')G.hp=Math.min(G.maxHp,G.hp+1);else if(d.type==='bomb')G.bombs=Math.min(G.maxBombs,G.bombs+1);else if(d.type==='bomb3')G.bombs=Math.min(G.maxBombs,G.bombs+3);else if(d.type==='key')G.keys++;else if(d.type==='rupee')G.rupees=Math.min(999,G.rupees+(d.value||1));else if(d.type==='rupeeChest'){G.rupees=Math.min(999,G.rupees+(d.value||0));G.taken.add(d.key);say(`${d.value} rupees found!`)}else if(d.type==='heartContainer'){G.taken.add(d.key);G.maxHp=Math.min(8,G.maxHp+1);G.hp=G.maxHp;say('Maximum health increased!')}else if(d.type==='bombBag'){G.taken.add(d.key);G.maxBombs=Math.min(16,G.maxBombs+4);G.bombs=G.maxBombs;say('Bomb capacity increased!')}else if(d.type==='windDisc'){G.taken.add(d.key);G.items.add('disc');G.selected='disc';say('Wind Disc acquired — B now throws it!')}else if(d.type==='bladeCharm'){G.taken.add(d.key);say('Pearl Edge acquired — sword reach and power increased!',180)}else if(d.type==='shard'){if(!G.taken.has(d.key)){G.taken.add(d.key);G.shards++;say(`Ember Shard ${G.shards}/3 acquired!`,130)}}else if(d.type==='relic'){G.final=true;G.taken.add(d.key);say('THE EMBER RELIC IS RESTORED!',240)}saveGame()}}};
update=function(){readGamepad();if(screenShake)screenShake--;if(mapOpen)return;if(slide){if(++slide.frame>=slide.total)finishSlide();return}if(transitionCooldown)transitionCooldown--;if(invuln)invuln--;if(messageTimer)messageTimer--;let dx=joyX+gpX,dy=joyY+gpY;if(KEYS.has('ArrowLeft')||KEYS.has('KeyA'))dx--;if(KEYS.has('ArrowRight')||KEYS.has('KeyD'))dx++;if(KEYS.has('ArrowUp')||KEYS.has('KeyW'))dy--;if(KEYS.has('ArrowDown')||KEYS.has('KeyS'))dy++;const m=Math.hypot(dx,dy);if(m>.08){dx/=Math.max(1,m);dy/=Math.max(1,m);face=Math.atan2(dy,dx);const speed=attack?.68:1.35,nx=x+dx*speed,ny=y+dy*speed;if(canMove(nx,y))x=nx;if(canMove(x,ny))y=ny;walk+=speed;pushRock(dx,dy)}else push={key:'',frames:0};
 if(!insideKey){if(x<-6)startSlide(-1,0);else if(x>246)startSlide(1,0);else if(y<-6)startSlide(0,-1);else if(y>230)startSlide(0,1)}else if(INTERIORS[insideKey]?.dungeon){if(!transitionCooldown){if(x<8&&dungeonLink('L'))dungeonTransition(-1,0);else if(x>232&&dungeonLink('R'))dungeonTransition(1,0);else if(y<8&&dungeonLink('U'))dungeonTransition(0,-1);else if(y>216&&dungeonLink('D'))dungeonTransition(0,1);else if(INTERIORS[insideKey]?.entry&&y>194&&x>104&&x<144)leaveInterior()}}else if(!transitionCooldown&&y>194&&x>104&&x<144)leaveInterior();checkPortal();unlockNearby();
 const A=KEYS.has('Space')||KEYS.has('Enter')||gpA;if(insideKey==='shop'){if(KEYS.has('ArrowLeft')||joyX<-.6)shopCursor=0;if(KEYS.has('ArrowUp')||joyY<-.6)shopCursor=1;if(KEYS.has('ArrowRight')||joyX>.6)shopCursor=2;shopUpdate()}else if(A&&!attackLatch&&!attack){if(typeof tryTalkNpc==='function'&&tryTalkNpc()){}else{sfx('sword');attack=14;for(const e of state().enemies)e.hit=false;if(G.hp===G.maxHp)waves.push({x:x+8+Math.cos(face)*18,y:y+8+Math.sin(face)*18,vx:Math.cos(face)*2.5,vy:Math.sin(face)*2.5,life:55,enemy:false})}}attackLatch=A;if(attack)attack--;const B=KEYS.has('KeyB')||KEYS.has('ShiftLeft')||gpB;if(B&&!bombLatch&&insideKey!=='shop')useBItem();bombLatch=B;
 const sw=swordLine();for(const e of state().enemies){if(!sw){e.hit=false;continue}if(e.hp>0&&!e.hit&&segmentDistance(e.x+7,e.y+7,...sw)<11){e.hit=true;damageEnemy(e,G.taken.has('reward:tide5')?2:1)}}updateEnemies();updateDrops();for(const b of bombObjs)if(--b.fuse===0)explode(b);bombObjs=bombObjs.filter(b=>b.fuse>0);for(const f of effects)f.t++;effects=effects.filter(f=>f.t<32);updateWaves();updateDiscs();if(performance.now()-lastSave>5000)saveGame()};
