/* Relic of Emberwood v40 Atlas Renderer
   Applies generated illustrated sprite/object atlases to the live game.
   Gameplay, maps, collision and progression remain unchanged. */
(function(){
const TAU=Math.PI*2;
const V40_WORLD={"tree_small":{"col":0,"row":0},"tree_large":{"col":1,"row":0},"dead_tree":{"col":2,"row":0},"bush":{"col":3,"row":0},"burn_bush":{"col":4,"row":0},"stump":{"col":5,"row":0},"grass":{"col":6,"row":0},"flowers":{"col":7,"row":0},"rock_small":{"col":0,"row":1},"rock_large":{"col":1,"row":1},"cliff":{"col":2,"row":1},"cave":{"col":3,"row":1},"grave":{"col":4,"row":1},"ruin":{"col":5,"row":1},"bridge":{"col":6,"row":1},"well":{"col":7,"row":1},"sign":{"col":0,"row":2},"house":{"col":1,"row":2},"shop":{"col":2,"row":2},"fence":{"col":3,"row":2},"barrel":{"col":4,"row":2},"jar":{"col":5,"row":2},"crate":{"col":6,"row":2},"chest_closed":{"col":7,"row":2},"chest_open":{"col":0,"row":3},"log":{"col":1,"row":3},"bomb":{"col":2,"row":3},"coin":{"col":3,"row":3},"rupee_green":{"col":4,"row":3},"rupee_blue":{"col":5,"row":3},"heart":{"col":6,"row":3},"potion_red":{"col":7,"row":3},"potion_blue":{"col":0,"row":4},"magic":{"col":1,"row":4},"key":{"col":2,"row":4},"bag":{"col":3,"row":4},"leaves":{"col":4,"row":4}};
const V40_DUNGEON={"door_open":{"col":0,"row":0},"door_closed":{"col":1,"row":0},"door_locked":{"col":2,"row":0},"boss_gate":{"col":3,"row":0},"barred_gate":{"col":4,"row":0},"wall":{"col":5,"row":0},"cracked_wall":{"col":6,"row":0},"stairs_down":{"col":7,"row":0},"stairs_up":{"col":0,"row":1},"ladder":{"col":1,"row":1},"pit":{"col":2,"row":1},"push_block":{"col":3,"row":1},"pressure":{"col":4,"row":1},"eye_switch":{"col":5,"row":1},"spikes":{"col":6,"row":1},"blade_trap":{"col":7,"row":1},"statue":{"col":0,"row":2},"knight_statue":{"col":1,"row":2},"angel_statue":{"col":2,"row":2},"pillar":{"col":3,"row":2},"broken_pillar":{"col":4,"row":2},"rubble":{"col":5,"row":2},"torch":{"col":6,"row":2},"brazier":{"col":7,"row":2},"lantern":{"col":0,"row":3},"altar":{"col":1,"row":3},"key_pedestal":{"col":2,"row":3},"chest_closed":{"col":3,"row":3},"chest_open":{"col":4,"row":3},"key_shrine":{"col":5,"row":3},"arch":{"col":6,"row":3},"broken_arch":{"col":7,"row":3},"wall_corner":{"col":0,"row":4},"wall_short":{"col":1,"row":4},"floor_plain":{"col":2,"row":4},"floor_moss":{"col":3,"row":4},"floor_cracked":{"col":4,"row":4},"floor_rubble":{"col":5,"row":4},"floor_glyph":{"col":6,"row":4},"floor_grate":{"col":7,"row":4},"floor_dirt":{"col":0,"row":5},"floor_water":{"col":1,"row":5},"floor_bones":{"col":2,"row":5},"floor_roots":{"col":3,"row":5}};
const V40_UI={"sword":{"col":0,"row":0},"pearl":{"col":1,"row":0},"bow":{"col":2,"row":0},"rod":{"col":3,"row":0},"disc":{"col":4,"row":0},"candle":{"col":5,"row":0},"bomb":{"col":6,"row":0},"key_small":{"col":7,"row":0},"key_master":{"col":8,"row":0},"shield":{"col":9,"row":0},"boots":{"col":0,"row":1},"moon_ring":{"col":1,"row":1},"sun_ring":{"col":2,"row":1},"tide_ring":{"col":3,"row":1},"shadow_ring":{"col":4,"row":1},"shard":{"col":5,"row":1},"map":{"col":6,"row":1},"compass":{"col":7,"row":1},"rupee_green":{"col":8,"row":1},"rupee_blue":{"col":9,"row":1},"coin":{"col":0,"row":2},"potion_red":{"col":1,"row":2},"potion_blue":{"col":2,"row":2},"potion_green":{"col":3,"row":2},"potion_gold":{"col":4,"row":2},"fairy_bottle":{"col":5,"row":2},"tunic_green":{"col":6,"row":2},"tunic_red":{"col":7,"row":2},"tunic_blue":{"col":8,"row":2},"tunic_purple":{"col":9,"row":2},"heart_full":{"col":0,"row":3},"heart_half":{"col":1,"row":3},"heart_empty":{"col":2,"row":3},"trophy_leaf":{"col":3,"row":3},"trophy_rabbit":{"col":4,"row":3},"trophy_crab":{"col":5,"row":3},"trophy_mushroom":{"col":6,"row":3},"trophy_boar":{"col":7,"row":3},"trophy_wisp":{"col":8,"row":3},"trophy_skeleton":{"col":9,"row":3},"trophy_imp":{"col":0,"row":4},"trophy_warden":{"col":1,"row":4},"trophy_lich":{"col":2,"row":4},"slash1":{"col":3,"row":4},"slash2":{"col":4,"row":4},"slash3":{"col":5,"row":4},"slash4":{"col":6,"row":4},"hit_spark":{"col":7,"row":4},"pickup_spark":{"col":8,"row":4},"fire1":{"col":9,"row":4},"fire2":{"col":0,"row":5},"fire3":{"col":1,"row":5},"fire4":{"col":2,"row":5},"fire5":{"col":3,"row":5},"smoke1":{"col":4,"row":5},"water1":{"col":5,"row":5},"water2":{"col":6,"row":5},"water3":{"col":7,"row":5},"water4":{"col":8,"row":5},"dust1":{"col":9,"row":5},"dust2":{"col":0,"row":6},"dust3":{"col":1,"row":6},"arrow":{"col":2,"row":6},"arrow_trail":{"col":3,"row":6},"disc_trail":{"col":4,"row":6},"magic1":{"col":5,"row":6},"magic2":{"col":6,"row":6},"magic3":{"col":7,"row":6},"magic4":{"col":8,"row":6},"explosion1":{"col":9,"row":6},"explosion2":{"col":0,"row":7},"explosion3":{"col":1,"row":7},"explosion4":{"col":2,"row":7},"smoke2":{"col":3,"row":7}};
const V40_EROW={"thornling":0,"fieldRunner":1,"mossBoar":2,"leafWisp":3,"stoneCrab":4,"ridgeArcher":5,"bogSpitter":6,"duskWisp":7,"shadeKnight":8,"emberImp":9,"coalHound":10,"bat":11,"slime":12,"walker":13,"bronzeSentry":14,"warden":15};
const V40_IMG={};
for(const [k,src] of Object.entries(window.V40_PACK_SRC||{})){const im=new Image();im.decoding='async';im.src=src;V40_IMG[k]=im;}
function ready(k){const im=V40_IMG[k];return !!(im&&im.complete&&im.naturalWidth)}
function cell(pack,map,name,dx,dy,dw,dh,a=1,rot=0){const im=V40_IMG[pack];const m=map[name];if(!m||!ready(pack))return false;const cs=pack==='uiPack'?64:(pack==='worldPack'||pack==='dungeonPack'?72:0);ctx.save();ctx.globalAlpha=a;ctx.translate(dx+dw/2,dy+dh/2);if(rot)ctx.rotate(rot);ctx.drawImage(im,m.col*cs,m.row*cs,cs,cs,-dw/2,-dh/2,dw,dh);ctx.restore();return true}
function frame(pack,sx,sy,sw,sh,dx,dy,dw,dh,a=1){const im=V40_IMG[pack];if(!ready(pack))return false;ctx.save();ctx.globalAlpha=a;ctx.drawImage(im,sx,sy,sw,sh,dx,dy,dw,dh);ctx.restore();return true}
function norm(v,m){v%=m;if(v<0)v+=m;return v}
function faceFloat(n){return norm(((face-Math.PI/2)/TAU)*n,n)}
function enemyAngle(e){if(Number.isFinite(e.vx)||Number.isFinite(e.vy))return Math.atan2(e.vy||0,e.vx||0);return [0,Math.PI/2,Math.PI,-Math.PI/2][(e.dir||0)&3]||0}
function angleFloat(a,n){return norm(((a-Math.PI/2)/TAU)*n,n)}
function shadow(cx,fy,rx,ry=.22){if(typeof v38Shadow==='function')v38Shadow(cx,fy,rx,Math.max(1.3,rx*.3),ry)}
const _hero=drawHero;
drawHero=function(){if(invuln&&((invuln/4)|0)%2)return;if(!ready('heroPack'))return _hero();const row=G.outfit==='emberTunic'?1:G.outfit==='tideTunic'?2:G.outfit==='shadowCloak'?3:0;const f=faceFloat(10),a=Math.floor(f),b=(a+1)%10,t=f-a;const moving=walk>0&&!attack;const bob=moving?Math.sin(walk*.8)*.6:0,cx=x+8,fy=y+17,w=27,h=38;shadow(cx,fy,7.8,.27);frame('heroPack',a*48,row*64,48,64,cx-w/2,fy-h+bob,w,h,1-t);frame('heroPack',b*48,row*64,48,64,cx-w/2,fy-h+bob,w,h,t)};
const EMAP={walker:'walker',knight:'shadeKnight',slime:'slime',bat:'bat',hopper:'fieldRunner',shrub:'thornling',thornling:'thornling',fieldRunner:'fieldRunner',mossBoar:'mossBoar',leafWisp:'leafWisp',stoneCrab:'stoneCrab',ridgeArcher:'ridgeArcher',mireLeech:'slime',bogSpitter:'bogSpitter',duskWisp:'duskWisp',shadeKnight:'shadeKnight',bronzeSentry:'bronzeSentry',ruinCrawler:'stoneCrab',emberImp:'emberImp',coalHound:'coalHound',galeHawk:'bat',cliffRam:'mossBoar',warden:'warden',rootLord:'warden',crystalMaw:'stoneCrab',stormEye:'duskWisp',forgeLord:'emberImp',moonKnight:'shadeKnight',emberSovereign:'warden'};
const ESIZE={thornling:[21,22],fieldRunner:[26,20],mossBoar:[31,24],leafWisp:[22,22],stoneCrab:[29,23],ridgeArcher:[24,27],slime:[28,20],bogSpitter:[25,23],duskWisp:[23,25],shadeKnight:[25,30],emberImp:[22,26],coalHound:[32,24],bat:[27,21],walker:[25,29],bronzeSentry:[29,32],warden:[44,46]};
const _enemy=drawEnemy;
drawEnemy=function(e){if(e.flash&&((e.flash/2)|0)%2)return;const fam=EMAP[e.v37Variant||e.type];if(!fam||V40_EROW[fam]==null||!ready('enemyPack'))return _enemy(e);const ang=enemyAngle(e),ff=angleFloat(ang,8),a=Math.floor(ff),b=(a+1)%8,t=ff-a,row=V40_EROW[fam];let [w,h]=ESIZE[fam]||[25,25];if(e.maxHp){w*=1.28;h*=1.28}const cx=e.x+7,fy=e.y+15,bob=(fam==='bat'||fam==='duskWisp'||fam==='leafWisp')?Math.sin(performance.now()/170+e.x)*1.2:0;if(!['bat','duskWisp','leafWisp'].includes(fam))shadow(cx,fy,Math.max(5,w*.3),.2);frame('enemyPack',a*56,row*56,56,56,cx-w/2,fy-h+bob,w,h,1-t);frame('enemyPack',b*56,row*56,56,56,cx-w/2,fy-h+bob,w,h,t)};
tree=function(X,Y){const large=((X+Y+(typeof id==='number'?id:0))>>4)%3===0;const n=large?'tree_large':'tree_small';shadow(X+8,Y+15,8,.2);if(!cell('worldPack',V40_WORLD,n,X-8,Y-(large?18:13),32,large?40:35)){rect(X+4,Y+5,8,10,'#376b3a')}};
rock=function(X,Y){const n=((X+Y)>>4)%3===0?'rock_large':'rock_small';shadow(X+8,Y+14,6,.18);if(!cell('worldPack',V40_WORLD,n,X-2,Y-2,20,18))rect(X+2,Y+4,12,10,'#777')};
ruin=function(X,Y){if(!cell('worldPack',V40_WORLD,'ruin',X-4,Y-7,24,24))rect(X+1,Y+2,14,13,'#77705d')};
grave=function(X,Y){if(!cell('worldPack',V40_WORLD,'grave',X-2,Y-7,20,24))rect(X+4,Y+3,8,12,'#747b75')};
reed=function(X,Y){if(!cell('worldPack',V40_WORLD,'grass',X-2,Y-3,20,20))rect(X+2,Y+8,12,7,'#345f35')};
cave=function(X,Y){shadow(X+8,Y+15,9,.24);if(!cell('worldPack',V40_WORLD,'cave',X-8,Y-13,32,30))rect(X+2,Y+5,12,11,'#030403')};
stairs=function(X,Y){if(!cell('dungeonPack',V40_DUNGEON,'stairs_down',X-5,Y-9,26,27))rect(X+1,Y+1,14,14,'#756e5d')};
door=function(X,Y,open=false){const n=open?'door_open':'door_closed';if(!cell('dungeonPack',V40_DUNGEON,n,X-5,Y-10,26,28))rect(X+2,Y+1,12,15,open?'#111':'#745032')};
shopDoor=function(X,Y){if(!cell('worldPack',V40_WORLD,'shop',X-12,Y-17,40,33))rect(X+2,Y+2,12,14,'#151515')};
shrineGate=function(X,Y,open){open=G&&G.shards>=SHARD_GOAL;const n=open?'door_open':'boss_gate';if(!cell('dungeonPack',V40_DUNGEON,n,X-6,Y-12,28,30))rect(X+2,Y+2,12,14,open?'#080808':'#302036')};
if(typeof drawV37Brush==='function'){const old=drawV37Brush;drawV37Brush=function(X,Y,edge=false){if(!cell('worldPack',V40_WORLD,'burn_bush',X-2,Y-4,20,20))old(X,Y,edge)}}
function npc(cx,fy,tint,row=0){if(!ready('heroPack'))return;const f=Math.atan2((y+8)-fy,(x+8)-cx),ff=angleFloat(f,10),a=Math.floor(ff),w=22,h=31;shadow(cx,fy,5,.16);frame('heroPack',a*48,row*64,48,64,cx-w/2,fy-h,w,h,.98);ctx.save();ctx.globalCompositeOperation='source-atop';ctx.fillStyle=tint;ctx.fillRect(cx-w/2,fy-h,w,h);ctx.restore()}
const _world=drawWorld;
drawWorld=function(i,ox=0,oy=0){_world(i,ox,oy);ctx.save();ctx.translate(ox,oy);for(const o of WORLD[i].objects){const X=o.x*T,Y=o.y*T,k=worldKey(i,o.x,o.y);if(o.type==='house')cell('worldPack',V40_WORLD,'house',X-13,Y-18,42,36);else if(o.type==='well'||o.type==='villageWell')cell('worldPack',V40_WORLD,'well',X-6,Y-10,28,27);else if(o.type==='sign'||o.type==='signpost')cell('worldPack',V40_WORLD,'sign',X-4,Y-11,24,28);else if(o.type==='npcElder')npc(X+8,Y+16,'rgba(165,105,55,.20)',1);else if(o.type==='npcScout')npc(X+8,Y+16,'rgba(60,140,100,.18)',0);else if(o.type==='npcChild')npc(X+8,Y+16,'rgba(75,125,205,.18)',2);else if(o.type==='bombWall'&&!G.open.has(k))cell('dungeonPack',V40_DUNGEON,'cracked_wall',X-4,Y-7,24,24);else if(o.type==='lockedGate'&&!G.unlocked.has(k))cell('dungeonPack',V40_DUNGEON,'door_locked',X-4,Y-9,24,27);else if(o.type==='finalGate'&&G.shards<SHARD_GOAL)cell('dungeonPack',V40_DUNGEON,'boss_gate',X-5,Y-10,26,28)}ctx.restore()};
if(typeof drawPillar==='function')drawPillar=function(tx,ty,theme){const X=tx*T,Y=ty*T;cell('dungeonPack',V40_DUNGEON,'pillar',X-2,Y-10,20,28)};
if(typeof drawSpikes==='function')drawSpikes=function(tx,ty){const X=tx*T,Y=ty*T;cell('dungeonPack',V40_DUNGEON,'spikes',X,Y,16,16)};
if(typeof drawPot==='function')drawPot=function(tx,ty,broken){if(broken)return;const X=tx*T,Y=ty*T;cell('worldPack',V40_WORLD,'jar',X+1,Y+1,14,15)};
if(typeof drawChestSprite==='function')drawChestSprite=function(c){const X=c.x*T,Y=c.y*T,open=chestOpened(c);shadow(X+8,Y+14,6,.2);cell('dungeonPack',V40_DUNGEON,open?'chest_open':'chest_closed',X-1,Y-4,18,20)};
const DROP={heart:['ui','heart_full'],magic:['world','magic'],key:['world','key'],bomb:['ui','bomb'],bomb3:['ui','bomb'],rupee:['world','rupee_green'],shard:['ui','shard'],relic:['ui','shard'],heartContainer:['ui','heart_full'],bombBag:['world','bag'],windDisc:['ui','disc'],emberCandle:['ui','candle'],rupeeChest:['world','chest_open'],sunBow:['ui','bow'],emberRod:['ui','rod'],masterKey:['ui','key_master'],mirrorShield:['ui','shield'],stormBoots:['ui','boots'],moonRing:['ui','moon_ring'],verdantRing:['ui','sun_ring'],guardianRing:['ui','tide_ring'],tideTunic:['ui','tunic_blue'],emberTunic:['ui','tunic_red'],shadowCloak:['ui','tunic_purple'],bladeCharm:['ui','pearl']};
const _drops=drawDrops;
drawDrops=function(){if(!ready('worldPack')&&!ready('uiPack'))return _drops();for(const d of state().drops){if(d.got)continue;let m=DROP[d.type];if(d.type==='rupee')m=['world',d.value===5?'rupee_blue':'rupee_green'];if(!m){_drops();return}const X=d.x,Y=d.y,pack=m[0]==='ui'?'uiPack':'worldPack',map=m[0]==='ui'?V40_UI:V40_WORLD;const sz=['heartContainer','shard','relic'].includes(d.type)?19:15;shadow(X,Y+6,4.5,.13);cell(pack,map,m[1],X-sz/2,Y-sz/2,sz,sz)}};
if(typeof drawBIcon==='function'){const oldB=drawBIcon;drawBIcon=function(cx,cy,item){const n=item==='bomb'?'bomb':item==='disc'?'disc':item==='sunBow'?'bow':item==='emberRod'?'rod':item==='emberCandle'?'candle':null;if(n&&cell('uiPack',V40_UI,n,cx-8,cy-8,16,16))return;oldB(cx,cy,item)}}
if(typeof drawUnifiedBomb==='function')drawUnifiedBomb=function(cx,cy,fuse=70,scale=1){const s=15*scale;shadow(cx,cy+6,4.5,.18);if(!cell('uiPack',V40_UI,'bomb',cx-s/2,cy-s/2,s,s)){circle(cx,cy,5,'#20242b')}};
const _fx=drawExplosion;
drawExplosion=function(f){const t=f.t||0;if(f.kind==='step'){if(f.biome==='water'){const n=['water1','water2','water3','water4'][Math.min(3,(t/5)|0)];cell('uiPack',V40_UI,n,f.x-7,f.y-4,14,8,.75)}return}if(f.kind==='spark'||f.kind==='hitSpark'){cell('uiPack',V40_UI,f.kind==='spark'?'pickup_spark':'hit_spark',f.x-6,f.y-6,12,12,1-Math.min(1,t/18));return}if(f.kind==='burst'){cell('uiPack',V40_UI,'hit_spark',f.x-5,f.y-5,10,10,.8);for(let i=0;i<4;i++){const a=i*1.57+t*.08;cell('worldPack',V40_WORLD,'jar',f.x+Math.cos(a)*(3+t*.18)-2,f.y+Math.sin(a)*(3+t*.12)-2,4,4,.55)}return}if(f.kind==='bushBurn'){const n=['fire1','fire2','fire3','fire4','fire5'][Math.min(4,(t/5)|0)];cell('uiPack',V40_UI,n,f.x-9,f.y-12,18,22);return}if(f.small){cell('uiPack',V40_UI,'hit_spark',f.x-5,f.y-5,10,10);return}const n=['explosion1','explosion2','explosion3','explosion4'][Math.min(3,(t/7)|0)];if(!cell('uiPack',V40_UI,n,f.x-18,f.y-18,36,36))_fx(f)};
const _draw=draw;
draw=function(){_draw();if(titleOpen||mapOpen||inventoryOpen||slide)return;for(const b of bombObjs)drawUnifiedBomb(b.x,b.y,b.fuse,1);for(const z of waves){if(z.enemy){const n=(z.kind&&String(z.kind).includes('ember'))?'fire2':'magic2';cell('uiPack',V40_UI,n,z.x-5,z.y-5,10,10)}else if(z.kind==='arrow'){const a=Math.atan2(z.vy,z.vx);cell('uiPack',V40_UI,'arrow',z.x-9,z.y-3,18,6,1,a)}else if(z.kind==='fire')cell('uiPack',V40_UI,'fire2',z.x-6,z.y-6,12,12);else cell('uiPack',V40_UI,'magic1',z.x-5,z.y-5,10,10)}for(const d of discs){const a=(performance.now()/90)%TAU;cell('uiPack',V40_UI,'disc',d.x-7,d.y-7,14,14,1,a)}};
if(typeof drawTitle==='function'){const oldT=drawTitle;drawTitle=function(){oldT();ctx.fillStyle='#f3ddb0';ctx.font='bold 5px system-ui,sans-serif';ctx.textAlign='center';ctx.fillText('v40 · ILLUSTRATED 360° SPRITE ATLAS EDITION',128,233)}}
})();
